# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/pus/forenklet-deploy
replicas:
  min: 2
  max: 3
  cpuThresholdPercentage: 50
port: 8800
healthcheck:
  liveness:
    path: internal/isAlive
    initialDelay: 20
  readiness:
    path: internal/selftest
    initialDelay: 20
fasitResources:
  used:
  - alias: unleash-api
    resourceType: restservice
  - alias: bekkci_confluence
    resourceType: credential
  - alias: pus-github
    resourceType: applicationProperties